#!/usr/bin/env bash
#
# Generated by scripts/catalogue_rerun.py -- do not edit; regenerate.
#
#   scripts/run_rerun.sh <slurm_jobid>
#   MAX_CONC=6 scripts/run_rerun.sh <slurm_jobid>     # share the node
#
# One sweep_runner process per (stream, driver). Every point inside one shares a system
# matrix with its neighbours, so the factorisation is paid once per group rather than
# once per point -- that is the 169x the whole ordering of Phase 0 was chosen for.
#
# Concurrency is bounded by MEMORY, not by cores. A solve is single-threaded and node-06
# has 96 of them, but one factorised two-die session is 14.4 GB on the largest die here,
# so 4 processes fill a 70 GB budget. Sized on PEAK RSS, which runs ~1.3x steady
# (docs/evidence/session_memory.json) -- sizing on steady oversubscribes the node during
# exactly the factorisation transient that makes it peak.
#
# Restartable: a finished stream leaves a .done marker and is skipped on the next run.
set -uo pipefail
JOBID="${1:?usage: run_rerun.sh <slurm_jobid>}"
REPO=/mnt/nfs01/scratch/jbalma/MXL-HotGauge
OUT=/mnt/nfs01/scratch/jbalma/MXL-HotGauge/results/rerun_accel
MAX_CONC="${MAX_CONC:-4}"
mkdir -p "$OUT/logs"
log() { printf "[%s] %s\n" "$(date +%H:%M:%S)" "$*" | tee -a "$OUT/driver.log"; }
throttle() { while [ "$(jobs -rp | wc -l)" -ge "$MAX_CONC" ]; do sleep 20; done; }

log "=== catalogue re-run: 4 streams, max concurrency $MAX_CONC ==="
log "    estimated 12.7 h of solver work, 3.3 h wall"

# 19 point(s), ~3.02 h, 14.4 GB peak
if [ -f "$OUT/logs/sf00_accelerator_study.done" ]; then log "SKIP sf00_accelerator_study"; else
  throttle
  log "START sf00_accelerator_study (19 points)"
  srun --jobid="$JOBID" --overlap -n1 --cpu-bind=none bash -lc \
    ". $REPO/setup_environment.sh >/dev/null 2>&1 && cd $REPO && OMP_NUM_THREADS=1 python -u scripts/sweep_runner.py examples/accelerator_study.py /mnt/nfs01/scratch/jbalma/MXL-HotGauge/results/rerun_accel/sf00_accelerator_study.json --keep-going --out-root $OUT/sf00_accelerator_study > $OUT/logs/sf00_accelerator_study.log 2>&1 && touch $OUT/logs/sf00_accelerator_study.done" &
fi

# 18 point(s), ~2.87 h, 14.4 GB peak
if [ -f "$OUT/logs/sf01_accelerator_study.done" ]; then log "SKIP sf01_accelerator_study"; else
  throttle
  log "START sf01_accelerator_study (18 points)"
  srun --jobid="$JOBID" --overlap -n1 --cpu-bind=none bash -lc \
    ". $REPO/setup_environment.sh >/dev/null 2>&1 && cd $REPO && OMP_NUM_THREADS=1 python -u scripts/sweep_runner.py examples/accelerator_study.py /mnt/nfs01/scratch/jbalma/MXL-HotGauge/results/rerun_accel/sf01_accelerator_study.json --keep-going --out-root $OUT/sf01_accelerator_study > $OUT/logs/sf01_accelerator_study.log 2>&1 && touch $OUT/logs/sf01_accelerator_study.done" &
fi

# 18 point(s), ~2.87 h, 14.4 GB peak
if [ -f "$OUT/logs/sf02_accelerator_study.done" ]; then log "SKIP sf02_accelerator_study"; else
  throttle
  log "START sf02_accelerator_study (18 points)"
  srun --jobid="$JOBID" --overlap -n1 --cpu-bind=none bash -lc \
    ". $REPO/setup_environment.sh >/dev/null 2>&1 && cd $REPO && OMP_NUM_THREADS=1 python -u scripts/sweep_runner.py examples/accelerator_study.py /mnt/nfs01/scratch/jbalma/MXL-HotGauge/results/rerun_accel/sf02_accelerator_study.json --keep-going --out-root $OUT/sf02_accelerator_study > $OUT/logs/sf02_accelerator_study.log 2>&1 && touch $OUT/logs/sf02_accelerator_study.done" &
fi

# 17 point(s), ~2.72 h, 14.4 GB peak
if [ -f "$OUT/logs/sf03_accelerator_study.done" ]; then log "SKIP sf03_accelerator_study"; else
  throttle
  log "START sf03_accelerator_study (17 points)"
  srun --jobid="$JOBID" --overlap -n1 --cpu-bind=none bash -lc \
    ". $REPO/setup_environment.sh >/dev/null 2>&1 && cd $REPO && OMP_NUM_THREADS=1 python -u scripts/sweep_runner.py examples/accelerator_study.py /mnt/nfs01/scratch/jbalma/MXL-HotGauge/results/rerun_accel/sf03_accelerator_study.json --keep-going --out-root $OUT/sf03_accelerator_study > $OUT/logs/sf03_accelerator_study.log 2>&1 && touch $OUT/logs/sf03_accelerator_study.done" &
fi

log "all streams queued; waiting"
wait
log "=== catalogue re-run COMPLETE ==="

# P0.5 acceptance: every row must carry a placement stamp, so this generation of results
# is distinguishable from the last one by inspection rather than by date.
srun --jobid="$JOBID" --overlap bash -lc \
  ". $REPO/setup_environment.sh >/dev/null 2>&1 && cd $REPO && python scripts/collect_findings.py > $OUT/FINDINGS.txt 2>&1" || true
log "findings at $OUT/FINDINGS.txt"
