#!/usr/bin/env bash
#
# Generated by scripts/catalogue_rerun.py -- do not edit; regenerate.
#
#   scripts/run_rerun.sh <slurm_jobid>
#   MAX_CONC=6 scripts/run_rerun.sh <slurm_jobid>     # share the node
#
# One sweep_runner process per (stream, driver). Every point inside one shares a system
# matrix with its neighbours, so the factorisation is paid once per group rather than
# once per point -- that is the 169x the whole ordering of Phase 0 was chosen for.
#
# Concurrency is bounded by MEMORY, not by cores. A solve is single-threaded and node-06
# has 96 of them, but one factorised two-die session is 28.8 GB on the largest die here,
# so 6 processes fill a 200 GB budget. Sized on PEAK RSS, which runs ~1.3x steady
# (docs/evidence/session_memory.json) -- sizing on steady oversubscribes the node during
# exactly the factorisation transient that makes it peak.
#
# Restartable: a finished stream leaves a .done marker and is skipped on the next run.
set -uo pipefail
JOBID="${1:?usage: run_rerun.sh <slurm_jobid>}"
REPO=/mnt/nfs01/scratch/jbalma/MXL-HotGauge
OUT=/mnt/nfs01/scratch/jbalma/MXL-HotGauge/results/rerun_arm_D
MAX_CONC="${MAX_CONC:-6}"
mkdir -p "$OUT/logs"
log() { printf "[%s] %s\n" "$(date +%H:%M:%S)" "$*" | tee -a "$OUT/driver.log"; }
throttle() { while [ "$(jobs -rp | wc -l)" -ge "$MAX_CONC" ]; do sleep 20; done; }

log "=== catalogue re-run: 16 streams, max concurrency $MAX_CONC ==="
log "    estimated 20.2 h of solver work, 3.8 h wall"

# 11 point(s), ~5.30 h, 28.8 GB peak
if [ -f "$OUT/logs/sf04_mr_comparison.done" ]; then log "SKIP sf04_mr_comparison"; else
  throttle
  log "START sf04_mr_comparison (11 points)"
  srun --jobid="$JOBID" --overlap -n1 --cpu-bind=none bash -lc \
    ". $REPO/setup_environment.sh >/dev/null 2>&1 && cd $REPO && OMP_NUM_THREADS=1 python -u scripts/sweep_runner.py examples/mr_comparison.py /mnt/nfs01/scratch/jbalma/MXL-HotGauge/results/rerun_arm_D/sf04_mr_comparison.json --keep-going --out-root $OUT/sf04_mr_comparison > $OUT/logs/sf04_mr_comparison.log 2>&1 && touch $OUT/logs/sf04_mr_comparison.done" &
fi

# 9 point(s), ~4.41 h, 28.8 GB peak
if [ -f "$OUT/logs/sf05_mr_comparison.done" ]; then log "SKIP sf05_mr_comparison"; else
  throttle
  log "START sf05_mr_comparison (9 points)"
  srun --jobid="$JOBID" --overlap -n1 --cpu-bind=none bash -lc \
    ". $REPO/setup_environment.sh >/dev/null 2>&1 && cd $REPO && OMP_NUM_THREADS=1 python -u scripts/sweep_runner.py examples/mr_comparison.py /mnt/nfs01/scratch/jbalma/MXL-HotGauge/results/rerun_arm_D/sf05_mr_comparison.json --keep-going --out-root $OUT/sf05_mr_comparison > $OUT/logs/sf05_mr_comparison.log 2>&1 && touch $OUT/logs/sf05_mr_comparison.done" &
fi

# 39 point(s), ~3.53 h, 5.7 GB peak
if [ -f "$OUT/logs/sf00_mr_comparison.done" ]; then log "SKIP sf00_mr_comparison"; else
  throttle
  log "START sf00_mr_comparison (39 points)"
  srun --jobid="$JOBID" --overlap -n1 --cpu-bind=none bash -lc \
    ". $REPO/setup_environment.sh >/dev/null 2>&1 && cd $REPO && OMP_NUM_THREADS=1 python -u scripts/sweep_runner.py examples/mr_comparison.py /mnt/nfs01/scratch/jbalma/MXL-HotGauge/results/rerun_arm_D/sf00_mr_comparison.json --keep-going --out-root $OUT/sf00_mr_comparison > $OUT/logs/sf00_mr_comparison.log 2>&1 && touch $OUT/logs/sf00_mr_comparison.done" &
fi

# 33 point(s), ~2.99 h, 5.7 GB peak
if [ -f "$OUT/logs/sf01_mr_comparison.done" ]; then log "SKIP sf01_mr_comparison"; else
  throttle
  log "START sf01_mr_comparison (33 points)"
  srun --jobid="$JOBID" --overlap -n1 --cpu-bind=none bash -lc \
    ". $REPO/setup_environment.sh >/dev/null 2>&1 && cd $REPO && OMP_NUM_THREADS=1 python -u scripts/sweep_runner.py examples/mr_comparison.py /mnt/nfs01/scratch/jbalma/MXL-HotGauge/results/rerun_arm_D/sf01_mr_comparison.json --keep-going --out-root $OUT/sf01_mr_comparison > $OUT/logs/sf01_mr_comparison.log 2>&1 && touch $OUT/logs/sf01_mr_comparison.done" &
fi

# 33 point(s), ~2.99 h, 5.7 GB peak
if [ -f "$OUT/logs/sf03_mr_comparison.done" ]; then log "SKIP sf03_mr_comparison"; else
  throttle
  log "START sf03_mr_comparison (33 points)"
  srun --jobid="$JOBID" --overlap -n1 --cpu-bind=none bash -lc \
    ". $REPO/setup_environment.sh >/dev/null 2>&1 && cd $REPO && OMP_NUM_THREADS=1 python -u scripts/sweep_runner.py examples/mr_comparison.py /mnt/nfs01/scratch/jbalma/MXL-HotGauge/results/rerun_arm_D/sf03_mr_comparison.json --keep-going --out-root $OUT/sf03_mr_comparison > $OUT/logs/sf03_mr_comparison.log 2>&1 && touch $OUT/logs/sf03_mr_comparison.done" &
fi

# 31 point(s), ~2.81 h, 5.7 GB peak
if [ -f "$OUT/logs/sf02_mr_comparison.done" ]; then log "SKIP sf02_mr_comparison"; else
  throttle
  log "START sf02_mr_comparison (31 points)"
  srun --jobid="$JOBID" --overlap -n1 --cpu-bind=none bash -lc \
    ". $REPO/setup_environment.sh >/dev/null 2>&1 && cd $REPO && OMP_NUM_THREADS=1 python -u scripts/sweep_runner.py examples/mr_comparison.py /mnt/nfs01/scratch/jbalma/MXL-HotGauge/results/rerun_arm_D/sf02_mr_comparison.json --keep-going --out-root $OUT/sf02_mr_comparison > $OUT/logs/sf02_mr_comparison.log 2>&1 && touch $OUT/logs/sf02_mr_comparison.done" &
fi

# 3 point(s), ~0.31 h, 5.7 GB peak
if [ -f "$OUT/logs/sf04_clock_headroom.done" ]; then log "SKIP sf04_clock_headroom"; else
  throttle
  log "START sf04_clock_headroom (3 points)"
  srun --jobid="$JOBID" --overlap -n1 --cpu-bind=none bash -lc \
    ". $REPO/setup_environment.sh >/dev/null 2>&1 && cd $REPO && OMP_NUM_THREADS=1 python -u scripts/sweep_runner.py examples/clock_headroom.py /mnt/nfs01/scratch/jbalma/MXL-HotGauge/results/rerun_arm_D/sf04_clock_headroom.json --keep-going --out-root $OUT/sf04_clock_headroom > $OUT/logs/sf04_clock_headroom.log 2>&1 && touch $OUT/logs/sf04_clock_headroom.done" &
fi

# 6 point(s), ~0.20 h, 2.8 GB peak
if [ -f "$OUT/logs/sf02_thermal_tiers.done" ]; then log "SKIP sf02_thermal_tiers"; else
  throttle
  log "START sf02_thermal_tiers (6 points)"
  srun --jobid="$JOBID" --overlap -n1 --cpu-bind=none bash -lc \
    ". $REPO/setup_environment.sh >/dev/null 2>&1 && cd $REPO && OMP_NUM_THREADS=1 python -u scripts/sweep_runner.py examples/thermal_tiers.py /mnt/nfs01/scratch/jbalma/MXL-HotGauge/results/rerun_arm_D/sf02_thermal_tiers.json --keep-going --out-root $OUT/sf02_thermal_tiers > $OUT/logs/sf02_thermal_tiers.log 2>&1 && touch $OUT/logs/sf02_thermal_tiers.done" &
fi

# 1 point(s), ~0.13 h, 5.7 GB peak
if [ -f "$OUT/logs/sf01_clock_headroom.done" ]; then log "SKIP sf01_clock_headroom"; else
  throttle
  log "START sf01_clock_headroom (1 points)"
  srun --jobid="$JOBID" --overlap -n1 --cpu-bind=none bash -lc \
    ". $REPO/setup_environment.sh >/dev/null 2>&1 && cd $REPO && OMP_NUM_THREADS=1 python -u scripts/sweep_runner.py examples/clock_headroom.py /mnt/nfs01/scratch/jbalma/MXL-HotGauge/results/rerun_arm_D/sf01_clock_headroom.json --keep-going --out-root $OUT/sf01_clock_headroom > $OUT/logs/sf01_clock_headroom.log 2>&1 && touch $OUT/logs/sf01_clock_headroom.done" &
fi

# 1 point(s), ~0.13 h, 5.7 GB peak
if [ -f "$OUT/logs/sf02_clock_headroom.done" ]; then log "SKIP sf02_clock_headroom"; else
  throttle
  log "START sf02_clock_headroom (1 points)"
  srun --jobid="$JOBID" --overlap -n1 --cpu-bind=none bash -lc \
    ". $REPO/setup_environment.sh >/dev/null 2>&1 && cd $REPO && OMP_NUM_THREADS=1 python -u scripts/sweep_runner.py examples/clock_headroom.py /mnt/nfs01/scratch/jbalma/MXL-HotGauge/results/rerun_arm_D/sf02_clock_headroom.json --keep-going --out-root $OUT/sf02_clock_headroom > $OUT/logs/sf02_clock_headroom.log 2>&1 && touch $OUT/logs/sf02_clock_headroom.done" &
fi

# 1 point(s), ~0.13 h, 5.7 GB peak
if [ -f "$OUT/logs/sf03_clock_headroom.done" ]; then log "SKIP sf03_clock_headroom"; else
  throttle
  log "START sf03_clock_headroom (1 points)"
  srun --jobid="$JOBID" --overlap -n1 --cpu-bind=none bash -lc \
    ". $REPO/setup_environment.sh >/dev/null 2>&1 && cd $REPO && OMP_NUM_THREADS=1 python -u scripts/sweep_runner.py examples/clock_headroom.py /mnt/nfs01/scratch/jbalma/MXL-HotGauge/results/rerun_arm_D/sf03_clock_headroom.json --keep-going --out-root $OUT/sf03_clock_headroom > $OUT/logs/sf03_clock_headroom.log 2>&1 && touch $OUT/logs/sf03_clock_headroom.done" &
fi

# 1 point(s), ~0.13 h, 5.7 GB peak
if [ -f "$OUT/logs/sf05_clock_headroom.done" ]; then log "SKIP sf05_clock_headroom"; else
  throttle
  log "START sf05_clock_headroom (1 points)"
  srun --jobid="$JOBID" --overlap -n1 --cpu-bind=none bash -lc \
    ". $REPO/setup_environment.sh >/dev/null 2>&1 && cd $REPO && OMP_NUM_THREADS=1 python -u scripts/sweep_runner.py examples/clock_headroom.py /mnt/nfs01/scratch/jbalma/MXL-HotGauge/results/rerun_arm_D/sf05_clock_headroom.json --keep-going --out-root $OUT/sf05_clock_headroom > $OUT/logs/sf05_clock_headroom.log 2>&1 && touch $OUT/logs/sf05_clock_headroom.done" &
fi

# 3 point(s), ~0.11 h, 2.8 GB peak
if [ -f "$OUT/logs/sf01_stacked_memory_study.done" ]; then log "SKIP sf01_stacked_memory_study"; else
  throttle
  log "START sf01_stacked_memory_study (3 points)"
  srun --jobid="$JOBID" --overlap -n1 --cpu-bind=none bash -lc \
    ". $REPO/setup_environment.sh >/dev/null 2>&1 && cd $REPO && OMP_NUM_THREADS=1 python -u scripts/sweep_runner.py examples/stacked_memory_study.py /mnt/nfs01/scratch/jbalma/MXL-HotGauge/results/rerun_arm_D/sf01_stacked_memory_study.json --keep-going --out-root $OUT/sf01_stacked_memory_study > $OUT/logs/sf01_stacked_memory_study.log 2>&1 && touch $OUT/logs/sf01_stacked_memory_study.done" &
fi

# 3 point(s), ~0.11 h, 2.8 GB peak
if [ -f "$OUT/logs/sf03_stacked_memory_study.done" ]; then log "SKIP sf03_stacked_memory_study"; else
  throttle
  log "START sf03_stacked_memory_study (3 points)"
  srun --jobid="$JOBID" --overlap -n1 --cpu-bind=none bash -lc \
    ". $REPO/setup_environment.sh >/dev/null 2>&1 && cd $REPO && OMP_NUM_THREADS=1 python -u scripts/sweep_runner.py examples/stacked_memory_study.py /mnt/nfs01/scratch/jbalma/MXL-HotGauge/results/rerun_arm_D/sf03_stacked_memory_study.json --keep-going --out-root $OUT/sf03_stacked_memory_study > $OUT/logs/sf03_stacked_memory_study.log 2>&1 && touch $OUT/logs/sf03_stacked_memory_study.done" &
fi

# 3 point(s), ~0.11 h, 2.8 GB peak
if [ -f "$OUT/logs/sf05_stacked_memory_study.done" ]; then log "SKIP sf05_stacked_memory_study"; else
  throttle
  log "START sf05_stacked_memory_study (3 points)"
  srun --jobid="$JOBID" --overlap -n1 --cpu-bind=none bash -lc \
    ". $REPO/setup_environment.sh >/dev/null 2>&1 && cd $REPO && OMP_NUM_THREADS=1 python -u scripts/sweep_runner.py examples/stacked_memory_study.py /mnt/nfs01/scratch/jbalma/MXL-HotGauge/results/rerun_arm_D/sf05_stacked_memory_study.json --keep-going --out-root $OUT/sf05_stacked_memory_study > $OUT/logs/sf05_stacked_memory_study.log 2>&1 && touch $OUT/logs/sf05_stacked_memory_study.done" &
fi

# 2 point(s), ~0.08 h, 2.8 GB peak
if [ -f "$OUT/logs/sf02_stacked_memory_study.done" ]; then log "SKIP sf02_stacked_memory_study"; else
  throttle
  log "START sf02_stacked_memory_study (2 points)"
  srun --jobid="$JOBID" --overlap -n1 --cpu-bind=none bash -lc \
    ". $REPO/setup_environment.sh >/dev/null 2>&1 && cd $REPO && OMP_NUM_THREADS=1 python -u scripts/sweep_runner.py examples/stacked_memory_study.py /mnt/nfs01/scratch/jbalma/MXL-HotGauge/results/rerun_arm_D/sf02_stacked_memory_study.json --keep-going --out-root $OUT/sf02_stacked_memory_study > $OUT/logs/sf02_stacked_memory_study.log 2>&1 && touch $OUT/logs/sf02_stacked_memory_study.done" &
fi

log "all streams queued; waiting"
wait
log "=== catalogue re-run COMPLETE ==="

# P0.5 acceptance: every row must carry a placement stamp, so this generation of results
# is distinguishable from the last one by inspection rather than by date.
srun --jobid="$JOBID" --overlap bash -lc \
  ". $REPO/setup_environment.sh >/dev/null 2>&1 && cd $REPO && python scripts/collect_findings.py > $OUT/FINDINGS.txt 2>&1" || true
log "findings at $OUT/FINDINGS.txt"
